apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
  name: {{ include "ftl.fullname" . }}-admin
  {{- if .Values.admin.service.annotations }}
  annotations:
    {{- toYaml .Values.admin.service.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http2
      port: {{ .Values.admin.service.port }}
      protocol: "TCP"
      targetPort: {{ .Values.admin.port }}
  selector:
    {{- include "ftl-admin.selectorLabels" . | nindent 4 }}
  type: ClusterIP
