{{- if .Values.console.enabled }}
{{ $version := printf "v%s" .Chart.Version -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ftl.fullname" . }}-console
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.console.replicas }}
  revisionHistoryLimit: {{ .Values.console.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "ftl-console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ftl-console.selectorLabels" . | nindent 8 }}
      annotations:
      {{- if .Values.console.podAnnotations }}
        {{- toYaml .Values.console.podAnnotations | nindent 8 }}
      {{- end }}
      {{ if .Values.istio.holdApplicationUntilProxyStarts }}
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.console.serviceAccountName }}
      containers:
        - name: app
          image: "{{ .Values.console.image.repository | default (printf "%s/%s" .Values.image.base .Values.console.image.name) }}:{{ .Values.console.image.tag | default .Values.image.tag | default $version }}"
          imagePullPolicy: {{ .Values.console.image.pullPolicy | default .Values.image.pullPolicy }}
          {{- if .Values.console.envFrom }}
          envFrom:
            {{- if .Values.console.envFrom }}
            {{- toYaml .Values.console.envFrom | nindent 12 }}
            {{- end }}
          {{- end }}
          env:
            {{- if .Values.console.env }}
            {{- toYaml .Values.console.env | nindent 12 }}
            {{- end }}
            - name: FTL_BIND
              value: "http://0.0.0.0:8892"
            - name: FTL_TIMELINE_ENDPOINT
              value: "http://{{ include "ftl.fullname" . }}-timeline:{{ .Values.timeline.port }}"
            - name: FTL_CONTROLLER_ENDPOINT
              value: "http://{{ include "ftl.fullname" . }}-controller:8892"
            - name: FTL_ENDPOINT
              value: "http://{{ include "ftl.fullname" . }}-admin:8892"
            - name: FTL_VERB_SERVICE_ENDPOINT
              value: "http://{{ include "ftl.fullname" . }}-controller:8892"
            - name: FTL_SCHEMA_ENDPOINT
              value: "http://{{ include "ftl.fullname" . }}-schema:{{ .Values.schema.services.schema.port }}"
            - name: LOG_LEVEL
              value: "{{ .Values.console.logLevel | default .Values.logLevel }}"
            - name: LOG_JSON
              value: "{{ .Values.console.logJson | default .Values.logJson }}"
          ports:
            - name: http2
              containerPort: 8892
              protocol: "TCP"
          {{- include "ftl.resources" .Values.console | nindent 10 }}
          {{- include "ftl.healthProbes" .Values.console | nindent 10 }}
          {{- include "ftl.securityContext" .Values.timeline | nindent 10 }}
      {{- include "ftl.commonPodConfig" .Values.console | nindent 6 }}

{{- end }}
