{{- if .Values.console.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
  name: {{ include "ftl.fullname" . }}-console
  {{- if .Values.console.service.annotations }}
  annotations:
    {{- toYaml .Values.console.service.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http2
      port: {{ .Values.console.port }}
      protocol: "TCP"
      targetPort: 8892
  selector:
    {{- include "ftl-console.selectorLabels" . | nindent 4 }}
  type: {{ .Values.console.service.type | default "ClusterIP" }}

{{- end }}
