{{ $version := printf "v%s" .Chart.Version -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ftl.fullname" . }}-controller
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicas }}
  revisionHistoryLimit: {{ .Values.controller.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "ftl-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ftl-controller.selectorLabels" . | nindent 8 }}
      annotations:
      {{- if .Values.controller.podAnnotations }}
        {{- toYaml .Values.controller.podAnnotations | nindent 8 }}
      {{- end }}
      {{ if .Values.istio.holdApplicationUntilProxyStarts }}
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.controller.serviceAccountName }}
      containers:
        - name: app
          image: "{{ .Values.controller.image.repository | default (printf "%s/%s" .Values.image.base .Values.controller.image.name) }}:{{ .Values.controller.image.tag | default .Values.image.tag | default $version }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy | default .Values.image.pullPolicy  }}
          {{- if .Values.controller.envFrom }}
          envFrom:
            {{- if .Values.controller.envFrom }}
            {{- toYaml .Values.controller.envFrom | nindent 12 }}
            {{- end }}
          {{- else if or .Values.secrets.logEncryptionKey .Values.secrets.asyncEncryptionKey }}
          envFrom:
            - secretRef:
                name: {{ include "ftl.fullname" . }}-secrets
          {{- end }}
          env:
            {{- if .Values.controller.env }}
            {{- toYaml .Values.controller.env | nindent 12 }}
            {{- end }}
            - name: FTL_TIMELINE_ENDPOINT
              value: "http://ftl-timeline:{{ .Values.timeline.port }}"
            - name: FTL_LEASE_ENDPOINT
              value: "http://ftl-lease:{{ .Values.lease.port }}"
            - name: FTL_ADMIN_ENDPOINT
              value: "http://ftl-admin:{{ .Values.admin.port }}"
            - name: FTL_SCHEMA_ENDPOINT
              value: "http://ftl-schema:{{ .Values.schema.services.schema.port }}"
            - name: FTL_ARTEFACT_REGISTRY
              value: "{{ .Values.registry.repository }}"
            - name: FTL_ARTEFACT_REGISTRY_ALLOW_INSECURE
              value: "{{ .Values.registry.allowInsecure }}"
            - name: FTL_ARTEFACT_REGISTRY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "ftl.fullname" . }}-secrets
                  key: FTL_CONTROLLER_REGISTRY_USERNAME
                  optional: true
            - name: FTL_ARTEFACT_REGISTRY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "ftl.fullname" . }}-secrets
                  key: FTL_CONTROLLER_REGISTRY_PASSWORD
                  optional: true
          ports:
            - name: http2
              containerPort: {{ .Values.controller.port }}
              protocol: "TCP"
          {{- include "ftl.resources" .Values.controller | nindent 10 }}
          {{- include "ftl.healthProbes" .Values.controller | nindent 10 }}
          {{- include "ftl.securityContext" .Values.timeline | nindent 10 }}
    {{- include "ftl.commonPodConfig" .Values.controller | nindent 6 }}
