apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
  name: {{ include "ftl.fullname" . }}-controller
  {{- if .Values.controller.service.annotations }}
  annotations:
    {{- toYaml .Values.controller.service.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: http2
      port: {{ .Values.controller.port }}
      protocol: "TCP"
      targetPort: {{ .Values.controller.port }}
  selector:
    {{- include "ftl-controller.selectorLabels" . | nindent 4 }}
  type: {{ .Values.controller.service.type | default "ClusterIP" }}
