{{ $version := printf "v%s" .Chart.Version -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ftl.fullname" . }}-cron
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cron.replicas }}
  podManagementPolicy: Parallel
  ordinals:
    start: 1
  revisionHistoryLimit: {{ .Values.cron.revisionHistoryLimit }}
  serviceName: ftl-cron-raft
  selector:
    matchLabels:
      {{- include "ftl-cron.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ftl-cron.selectorLabels" . | nindent 8 }}
      annotations:
      {{- if .Values.cron.podAnnotations }}
        {{- toYaml .Values.cron.podAnnotations | nindent 8 }}
      {{- end }}
      {{ if .Values.istio.holdApplicationUntilProxyStarts }}
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.cron.serviceAccountName }}
      securityContext:
        fsGroup: 1000
      containers:
        - name: app
          image: "{{ .Values.cron.image.repository | default (printf "%s/%s" .Values.image.base .Values.cron.image.name) }}:{{ .Values.cron.image.tag | default .Values.image.tag | default $version }}"
          imagePullPolicy: {{ .Values.cron.image.pullPolicy | default .Values.image.pullPolicy }}
          {{- if .Values.cron.envFrom }}
          envFrom:
            {{- if .Values.cron.envFrom }}
            {{- toYaml .Values.cron.envFrom | nindent 12 }}
            {{- end }}
          {{- end }}
          volumeMounts:
          - name: cron-raft-storage
            mountPath: /data/raft
          ports:
            - name: http
              containerPort: {{ .Values.cron.services.cron.containerPort }}
              protocol: TCP
            - name: raft
              containerPort: {{ .Values.cron.services.raft.containerPort }}
              protocol: TCP
          env:
            {{- if .Values.cron.env }}
            {{- toYaml .Values.cron.env | nindent 12 }}
            {{- end }}
            - name: FTL_BIND
              value: "http://0.0.0.0:{{ .Values.cron.services.cron.port }}"
            - name: FTL_TIMELINE_ENDPOINT
              value: "http://{{ include "ftl.fullname" . }}-timeline:{{ .Values.timeline.port }}"
            - name: FTL_SCHEMA_ENDPOINT
              value: "http://{{ include "ftl.fullname" . }}-schema:{{ $.Values.schema.services.schema.port }}"
            - name: LOG_LEVEL
              value: "{{ .Values.cron.logLevel | default .Values.logLevel }}"
            - name: LOG_JSON
              value: "{{ .Values.cron.logJson | default .Values.logJson }}"
            - name: RAFT_INITIAL_MEMBERS
              value: "{{- range $index := until (.Values.cron.replicas | int ) }}{{- if ne $index 0 -}},{{- end -}}ftl-cron-{{ add $index 1  }}.ftl-cron-raft:{{$.Values.cron.services.raft.port}}{{- end -}}"
            - name: RAFT_INITIAL_REPLICA_IDS
              value: "{{- range $index := until (.Values.cron.replicas | int ) }}{{- if ne $index 0 -}},{{- end -}}{{ add $index 1  }}{{- end -}}"
            - name: RAFT_DATA_DIR
              value: "/data/raft"
            - name: ORDINAL_NUMBER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            - name: RAFT_ADDRESS
              value: "{{ include "ftl.fullname" . }}-cron-$(ORDINAL_NUMBER).{{ include "ftl.fullname" . }}-cron-raft:{{$.Values.cron.services.raft.port}}"
            - name: RAFT_LISTEN_ADDRESS
              value: "0.0.0.0:{{$.Values.cron.services.raft.port}}"
            - name: RAFT_CONTROL_ADDRESS
              value: "http://{{ include "ftl.fullname" . }}-cron:{{ .Values.cron.services.cron.port }}"
          {{- include "ftl.resources" .Values.cron | nindent 10 }}
          {{- include "ftl.securityContext" .Values.cron | nindent 10 }}
      {{- include "ftl.commonPodConfig" .Values.cron | nindent 6 }}
  volumeClaimTemplates:
  - metadata:
      name: cron-raft-storage
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.cron.storage }}
