{{- if .Values.ingress.enabled }}
{{ $version := printf "v%s" .Chart.Version -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ftl.fullname" . }}-http-ingress
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.ingress.replicas }}
  revisionHistoryLimit: {{ .Values.ingress.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "ftl-http-ingress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ftl-http-ingress.selectorLabels" . | nindent 8 }}
      annotations:
      {{- if .Values.ingress.podAnnotations }}
        {{- toYaml .Values.ingress.podAnnotations | nindent 8 }}
      {{- end }}
      {{ if .Values.istio.holdApplicationUntilProxyStarts }}
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.ingress.serviceAccountName }}
      containers:
        - name: app
          image: "{{ .Values.ingress.image.repository | default (printf "%s/%s" .Values.image.base .Values.ingress.image.name) }}:{{ .Values.ingress.image.tag | default .Values.image.tag | default $version }}"
          imagePullPolicy: {{ .Values.ingress.image.pullPolicy | default .Values.image.pullPolicy  }}
          {{- if .Values.ingress.envFrom }}
          envFrom:
            {{- if .Values.ingress.envFrom }}
            {{- toYaml .Values.ingress.envFrom | nindent 12 }}
            {{- end }}
          {{- end }}
          env:
            {{- if .Values.ingress.env }}
            {{- toYaml .Values.ingress.env | nindent 12 }}
            {{- end }}
            - name: FTL_BIND
              value: "http://0.0.0.0:8892"
            - name: FTL_TIMELINE_ENDPOINT
              value: "http://{{ .Values.timeline.service.name }}:{{ .Values.timeline.service.port }}"
            - name: FTL_SCHEMA_ENDPOINT
              value: "http://ftl-schema:8892"

          ports:
            {{- range .Values.ingress.ports }}
            - name: {{ .name }}
              containerPort: 8892
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          {{- include "ftl.resources" .Values.ingress | nindent 10 }}
          {{- include "ftl.healthProbes" .Values.ingress | nindent 10 }}
          {{- include "ftl.securityContext" .Values.timeline | nindent 10 }}
      {{- include "ftl.commonPodConfig" .Values.ingress | nindent 6 }}


{{- end }}