{{ $version := printf "v%s" .Chart.Version -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ftl.fullname" . }}-lease
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.lease.replicas }}
  revisionHistoryLimit: {{ .Values.lease.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "ftl-lease.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ftl-lease.selectorLabels" . | nindent 8 }}
      annotations:
      {{- if .Values.lease.podAnnotations }}
        {{- toYaml .Values.lease.podAnnotations | nindent 8 }}
      {{- end }}
      {{ if .Values.istio.holdApplicationUntilProxyStarts }}
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.lease.serviceAccountName }}
      containers:
        - name: app
          image: "{{ .Values.lease.image.repository | default (printf "%s/%s" .Values.image.base .Values.lease.image.name) }}:{{ .Values.lease.image.tag | default .Values.image.tag | default $version }}"
          imagePullPolicy: {{ .Values.lease.image.pullPolicy }}
          resources:
            limits:
              cpu: "{{ .Values.lease.resources.limits.cpu }}"
              memory: "{{ .Values.lease.resources.limits.memory }}"
            requests:
              cpu: "{{ .Values.lease.resources.requests.cpu }}"
              memory: "{{ .Values.lease.resources.requests.memory }}"
          {{- if .Values.lease.envFrom }}
          envFrom:
            {{- if .Values.lease.envFrom }}
            {{- toYaml .Values.lease.envFrom | nindent 12 }}
            {{- end }}
          {{- end }}
          env:
            {{- if .Values.lease.env }}
            {{- toYaml .Values.lease.env | nindent 12 }}
            {{- end }}
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: FTL_BIND
              value: "http://0.0.0.0:8892"
            - name: LOG_LEVEL
              value: "{{ .Values.lease.logLevel }}"
            - name: LOG_JSON
              value: "{{ .Values.lease.logJson }}"
          ports:
            - name: "http2"
              containerPort: 8892
              hostPort: {{ .Values.lease.port }}
              protocol: "TCP"
          {{- include "ftl.healthProbes" .Values.lease | nindent 10 }}
          {{- include "ftl.securityContext" .Values.timeline | nindent 10 }}
      {{- include "ftl.commonPodConfig" .Values.lease | nindent 6 }}
