{{ $version := printf "v%s" .Chart.Version -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ftl.fullname" . }}-provisioner
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.provisioner.replicas }}
  revisionHistoryLimit: {{ .Values.provisioner.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "ftl-provisioner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ftl-provisioner.selectorLabels" . | nindent 8 }}
      annotations:
      {{- if .Values.provisioner.podAnnotations }}
        {{- toYaml .Values.provisioner.podAnnotations | nindent 8 }}
      {{- end }}
      {{ if .Values.istio.holdApplicationUntilProxyStarts }}
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.provisioner.serviceAccountName }}
      containers:
        - name: app
          image: "{{ .Values.provisioner.image.repository | default (printf "%s/%s" .Values.image.base .Values.provisioner.image.name) }}:{{ .Values.provisioner.image.tag | default .Values.image.tag | default $version }}"
          imagePullPolicy: {{ .Values.provisioner.image.pullPolicy }}
          {{- if .Values.provisioner.envFrom }}
          envFrom:
            {{- if .Values.provisioner.envFrom }}
            {{- toYaml .Values.provisioner.envFrom | nindent 12 }}
            {{- end }}
          {{- else if or .Values.secrets.logEncryptionKey .Values.secrets.asyncEncryptionKey }}
          envFrom:
            - secretRef:
                name: {{ include "ftl.fullname" . }}-secrets
          {{- end }}
          env:
            {{- if .Values.provisioner.env }}
            {{- toYaml .Values.provisioner.env | nindent 12 }}
            {{- end }}
          volumeMounts:
            - mountPath: /config
              name: config
      volumes:
        - name: config
          configMap:
            name: {{ .Values.provisioner.configMap }}
      {{- include "ftl.commonPodConfig" .Values.provisioner | nindent 6 }}
