{{- if eq .Values.provisioner.configMap "ftl-provisioner-default-config" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ftl-provisioner-default-config
  namespace: {{ .Release.Namespace }}
data:
  config.toml: |
    plugins = [
    {{- range .Values.provisioner.config.plugins }}
        { id = "{{ .id }}", resources = [{{ range $index, $resource := .resources }}{{ if $index }}, {{ end }}"{{ $resource }}"{{ end }}] },
    {{- end }}
    ]
{{- end}}