apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.provisioner.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.provisioner.provisionersRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.provisioner.provisionersRoleArn }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.realmName }}-{{ include "ftl.fullname" . }}-provisioner
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch", "delete", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "services" , "serviceaccounts"]
    verbs: [ "get", "list", "watch", "delete", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "pods/log" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames:
      - ftl-provisioner-deployment-config
    verbs: [ "get"]
  - apiGroups: [ "security.istio.io" ]
    resources: [ "authorizationpolicies" ]
    verbs: [ "get", "list", "watch", "delete", "create", "update", "patch" ]
  {{ if not .Values.provisioner.userNamespace }}
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: [ "get", "list", "watch", "create" ]
  {{- end}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.realmName }}-{{ .Release.Namespace }}-{{ include "ftl.fullname" . }}-provisioner
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.realmName }}-{{ include "ftl.fullname" . }}-provisioner
subjects:
  - kind: ServiceAccount
    name: {{ .Values.provisioner.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
