apiVersion: v1
kind: ConfigMap
metadata:
  name: ftl-provisioner-deployment-config
data:
  serviceTemplate: |-
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: "(replaced)"
      name: "(replaced)"
    spec:
      ports:
        - name: http2
          protocol: TCP
          port: 8892
          targetPort: {{ .Values.runner.port }}
      type: ClusterIP
  deploymentTemplate: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: {{ include "ftl.fullname" . }}-runner
      labels:
        {{- include "ftl.labels" . | nindent 8 }}
    spec:
      replicas: {{ .Values.runner.replicas }}
      revisionHistoryLimit: {{ .Values.runner.revisionHistoryLimit }}
      minReadySeconds: 30
      selector:
        matchLabels:
          {{- include "ftl-runner.selectorLabels" . | nindent 10 }}
      template:
        metadata:
          labels:
            {{- include "ftl-runner.selectorLabels" . | nindent 12 }}
          annotations:
          {{- if .Values.runner.podAnnotations }}
            {{- toYaml .Values.runner.podAnnotations | nindent 12 }}
          {{- end }}
          {{ if .Values.istio.holdApplicationUntilProxyStarts }}
            proxy.istio.io/config: |
              holdApplicationUntilProxyStarts: true
          {{- end }}
        spec:
          containers:
            - name: app
              image: "(replaced)"
              imagePullPolicy: {{ .Values.runner.image.pullPolicy | default .Values.image.pullPolicy }}
              resources:
                limits:
                  cpu: "{{ .Values.runner.resources.limits.cpu }}"
                  memory: "{{ .Values.runner.resources.limits.memory }}"
                requests:
                  cpu: "{{ .Values.runner.resources.requests.cpu }}"
                  memory: "{{ .Values.runner.resources.requests.memory }}"
              {{- if .Values.runner.envFrom }}
              envFrom:
                {{- toYaml .Values.runner.envFrom | nindent 16 }}
              {{- end }}
              env:
                {{ include "ftl-service.environment-variables" . | nindent 16 }}
                {{- if .Values.runner.env }}
                {{- toYaml .Values.runner.env | nindent 16 }}
                {{- end }}
                {{- if and .Values.istio.enabled .Values.provisioner.userNamespace }}
                - name: FTL_BIND
                  value: "unix://@istio-proxy.sock"
                - name: FTL_HEALTH_BIND
                  value: "http://0.0.0.0:{{ .Values.runner.port }}"
                {{- else }}
                - name: FTL_BIND
                  value: "http://0.0.0.0:{{ .Values.runner.port }}"
                {{- end }}
                - name: FTL_ENDPOINT
                  value: "http://{{ include "ftl.fullname" . }}-admin.{{ .Release.Namespace }}:{{ .Values.admin.port }}"
                - name: FTL_ARTEFACT_REGISTRY
                  value: "{{ .Values.registry.repository }}"
                - name: FTL_SCHEMA_ENDPOINT
                  value: {{ if $.Values.schemaMirror.service.enabled -}}
                    http://{{ include "ftl.fullname" . }}-schema-mirror.{{ .Release.Namespace }}:{{ $.Values.schemaMirror.service.port }}
                    {{- else -}}
                    http://{{ include "ftl.fullname" . }}-schema.{{ .Release.Namespace }}:{{ $.Values.schema.services.schema.port }}
                    {{- end }}
                - name: FTL_LEASE_ENDPOINT
                  value: http://{{ include "ftl.fullname" . }}-lease.{{ .Release.Namespace }}:{{ .Values.lease.port }}
                - name: FTL_TIMELINE_ENDPOINT
                  value: "http://{{ include "ftl.fullname" . }}-timeline.{{ .Release.Namespace }}:{{ .Values.timeline.port }}"
                - name: LOG_LEVEL
                  value: "{{ .Values.runner.logLevel | default .Values.logLevel }}"
                - name: LOG_JSON
                  value: "{{ .Values.runner.logJson | default .Values.logJson }}"
                - name: FTL_ARTEFACT_REGISTRY_ALLOW_INSECURE
                  value: "{{ .Values.registry.allowInsecure }}"
                - name: FTL_ARTEFACT_REGISTRY_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "ftl.fullname" . }}-secrets
                      key: FTL_RUNNER_REGISTRY_USERNAME
                      optional: true
                - name: FTL_ARTEFACT_REGISTRY_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "ftl.fullname" . }}-secrets
                      key: FTL_RUNNER_REGISTRY_PASSWORD
                      optional: true
              ports:
                - name: https
                  containerPort: {{ .Values.runner.port }}
                  protocol: "TCP"
              {{- include "ftl.healthProbes" .Values.timeline | nindent 14 }}
              {{- include "ftl.securityContext" .Values.cron | nindent 14 }}
              volumeMounts:
                - mountPath: /home/ubuntu/.cache
                  name: cache
                - mountPath: /tmp
                  name: tmp
          volumes:
            - name: cache
              emptyDir: {}
            - name: tmp
              emptyDir: {}
      {{- include "ftl.commonPodConfig" .Values.runner | nindent 10 }}
  serviceAccountTemplate: |-
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      labels:
        app: ftl-runner
      {{- if .Values.runner.runnersRoleArn }}
      annotations:
        eks.amazonaws.com/role-arn: {{ .Values.runner.runnersRoleArn }}
      {{- end }}
