{{ $version := printf "v%s" .Chart.Version -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "ftl.fullname" . }}-schema
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.schema.replicas }}
  podManagementPolicy: Parallel
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  ordinals:
    start: 1
  revisionHistoryLimit: {{ .Values.schema.revisionHistoryLimit }}
  serviceName: {{ .Values.schema.serviceName }}
  selector:
    matchLabels:
      {{- include "ftl-schema.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ftl-schema.selectorLabels" . | nindent 8 }}
      annotations:
      {{- if .Values.schema.podAnnotations }}
        {{- toYaml .Values.schema.podAnnotations | nindent 8 }}
      {{- end }}
      {{ if .Values.istio.holdApplicationUntilProxyStarts }}
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.schema.serviceAccountName }}
      containers:
        - name: app
          image: "{{ .Values.schema.image.repository }}:{{ .Values.schema.image.tag | default $version }}"
          imagePullPolicy: {{ .Values.schema.image.pullPolicy }}
          {{- if .Values.schema.envFrom }}
          envFrom:
            {{- if .Values.schema.envFrom }}
            {{- toYaml .Values.schema.envFrom | nindent 12 }}
            {{- end }}
          {{- else if or .Values.secrets.logEncryptionKey .Values.secrets.asyncEncryptionKey }}
          envFrom:
            - secretRef:
                name: {{ include "ftl.fullname" . }}-secrets
          {{- end }}
          env:
            {{- if .Values.schema.env }}
            {{- toYaml .Values.schema.env | nindent 12 }}
            {{- end }}
            - name: FTL_BIND
              value: "http://0.0.0.0:{{ .Values.schema.services.schema.containerPort }}"
            - name: RAFT_INITIAL_MEMBERS
              value: "{{- range $index := until (.Values.schema.replicas | int ) }}{{- if ne $index 0 -}},{{- end -}}ftl-schema-{{ add $index 1  }}.ftl-schema-raft:{{$.Values.schema.services.raft.port}}{{- end -}}"
            - name: RAFT_DATA_DIR
              value: "/tmp/ftl-schema-$(ORDINAL_NUMBER)"
            - name: ORDINAL_NUMBER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            - name: RAFT_ADDRESS
              value: "ftl-schema-$(ORDINAL_NUMBER).ftl-schema-raft:8992"
            - name: RAFT_REPLICA_ID
              value: "$(ORDINAL_NUMBER)"
            - name: RAFT_LISTEN_ADDRESS
              value: "$(MY_POD_IP):8992"
            - name: RAFT_CONTROL_ADDRESS
              value: "http://ftl-schema:8892"
          ports:
            - name: http
              containerPort: {{ .Values.schema.services.schema.containerPort }}
              protocol: "TCP"
            - name: raft
              containerPort: {{ .Values.schema.services.raft.containerPort }}
              protocol: "TCP"
          readinessProbe:
            {{- if .Values.schema.readinessProbe }}
            {{- toYaml .Values.schema.readinessProbe | nindent 12 }}
            {{- else }}
            httpGet:
              path: /healthz
              port: {{ .Values.schema.services.schema.containerPort }}
            initialDelaySeconds: 1
            periodSeconds: 2
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 15
            {{- end }}
      {{- if .Values.schema.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.schema.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.schema.affinity }}
      affinity:
        {{- toYaml .Values.schema.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.schema.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.schema.topologySpreadConstraints | nindent 8 }}
      {{- end }}
      {{- if .Values.schema.tolerations }}
      tolerations:
        {{- toYaml .Values.schema.tolerations | nindent 8 }}
      {{- end }}