{{- if .Values.timeline.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
  name: {{ include "ftl.fullname" . }}-timeline
  {{- if .Values.timeline.service.annotations }}
  annotations:
    {{- toYaml .Values.timeline.service.annotations | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: "http2"
      port: {{ .Values.timeline.port }}
      protocol: "TCP"
      targetPort: {{ .Values.timeline.port }}
  selector:
    {{- include "ftl-timeline.selectorLabels" . | nindent 4 }}
  type: "ClusterIP"

{{- end }}
