{{- if .Values.timeline.enabled }}
{{ $version := printf "v%s" .Chart.Version -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ftl.fullname" . }}-timeline
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.timeline.replicas }}
  revisionHistoryLimit: {{ .Values.timeline.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "ftl-timeline.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ftl-timeline.selectorLabels" . | nindent 8 }}
      annotations:
      {{- if .Values.timeline.podAnnotations }}
        {{- toYaml .Values.timeline.podAnnotations | nindent 8 }}
      {{- end }}
      {{ if .Values.istio.holdApplicationUntilProxyStarts }}
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.timeline.serviceAccountName }}
      containers:
        - name: app
          image: "{{ .Values.timeline.image.repository | default (printf "%s/%s" .Values.image.base .Values.timeline.image.name) }}:{{ .Values.timeline.image.tag | default .Values.image.tag | default $version }}"
          imagePullPolicy: {{ .Values.timeline.image.pullPolicy | default .Values.image.pullPolicy }}
          {{- if .Values.timeline.envFrom }}
          envFrom:
            {{- if .Values.timeline.envFrom }}
            {{- toYaml .Values.timeline.envFrom | nindent 12 }}
            {{- end }}
          {{- end }}
          env:
            {{- if .Values.timeline.env }}
            {{- toYaml .Values.timeline.env | nindent 12 }}
            {{- end }}

          ports:
            - name: http2
              containerPort: {{ .Values.timeline.port }}
              protocol: "TCP"
          {{- include "ftl.resources" .Values.timeline | nindent 10 }}
          {{- include "ftl.healthProbes" .Values.timeline | nindent 10 }}
          {{- include "ftl.securityContext" .Values.timeline | nindent 10 }}
      {{- include "ftl.commonPodConfig" .Values.timeline | nindent 6 }}

{{- end }}
