{{- if .Values.timeline.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.timeline.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.timeline.timelineRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.timeline.timelineRoleArn }}
  {{- end }}
{{- end }}
