{{- if .Values.provisioner.userNamespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ftl.fullname" . }}-provisioner
  namespace: {{ .Values.provisioner.userNamespace }}
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch", "delete", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "services" , "serviceaccounts"]
    verbs: [ "get", "list", "watch", "delete", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "pods/log" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    resourceNames:
      - ftl-provisioner-deployment-config
    verbs: [ "get"]
  - apiGroups: [ "security.istio.io" ]
    resources: [ "authorizationpolicies" ]
    verbs: [ "get", "list", "watch", "delete", "create", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    resourceNames: [ "{{ .Values.provisioner.userNamespace }}" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ftl.fullname" . }}-provisioner
  namespace:  {{ .Values.provisioner.userNamespace }}
  labels:
    {{- include "ftl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ftl.fullname" . }}-provisioner
subjects:
  - kind: ServiceAccount
    name: {{ .Values.provisioner.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
{{- end }}