apiVersion: v2
name: ftl-k3d
description: |
  A Helm chart for Kubernetes that deploys supplimental dependencies for k3d
home: https://github.com/block/ftl
version: 0.493.5
appVersion: 0.493.5
dependencies:
  - name: ftl
    version: 0.493.5
    repository: file://../ftl
