_help:
  @just -l

dep-update:
    helm dep update ftl

set-version version:
    @echo "Setting version to {{version}}"
    yq -i  '.version="{{version}}",.appVersion="{{version}}"' ftl/Chart.yaml
    yq -i  '.version="{{version}}",.appVersion="{{version}}"' ftl-k3d/Chart.yaml
    yq -i  '.dependencies[0].version="{{version}}"' ftl-k3d/Chart.yaml

package:
    helm lint ftl
    helm package -u ftl -d output
