apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ftl-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: ftl-console
              port:
                number: 8892
        - path: /ingress/
          pathType: Prefix
          backend:
            service:
              name: ftl-http-ingress
              port:
                number: 8891
        - path: /xyz.block.ftl.v1.VerbService/
          pathType: Prefix
          backend:
            service:
              name: ftl-admin
              port:
                number: 8892
        - path: /xyz.block.ftl.admin.v1.AdminService/
          pathType: Prefix
          backend:
            service:
              name: ftl-admin
              port:
                number: 8892
        - path: /xyz.block.ftl.timeline.v1.TimelineService
          pathType: Prefix
          backend:
            service:
              name: ftl-timeline
              port:
                number: 8892

